view: healthcare_bqml_input1 {
  derived_table: {
    sql: SELECT
    patient.id  AS patient_id,
    CONCAT((regexp_replace(patient.name[Offset(0)].given[Offset(0)],'[0-9]','')), ' ',(regexp_replace(patient.name[Offset(0)].family,'[0-9]','')))  AS patient_name,
    practitioner.gender  AS practitioner_gender,
    patient.us_core_race.text.value.string  AS patient_us_core_race,
    CASE
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 0 THEN '0'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 0 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 18 THEN '1'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 18 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 25 THEN '2'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 25 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 40 THEN '3'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 40 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 55 THEN '4'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 55 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 65 THEN '5'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 65 THEN '6'
ELSE '7'
END AS patient_age_tier__sort_,
    CASE
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 0 THEN 'Below 0'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 0 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 18 THEN '0 to 17'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 18 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 25 THEN '18 to 24'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 25 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 40 THEN '25 to 39'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 40 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 55 THEN '40 to 54'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 55 AND (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  < 65 THEN '55 to 64'
WHEN (CAST(CASE WHEN CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12 < 0 THEN CEILING(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) ELSE FLOOR(CAST((DATE_DIFF(DATE(CURRENT_TIMESTAMP() , 'America/Los_Angeles'), DATE(patient.birthDate , 'America/Los_Angeles'), MONTH) + CASE WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) = TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN 0 WHEN TIMESTAMP_DIFF(CURRENT_TIMESTAMP() , TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , MONTH, 'America/Los_Angeles'), SECOND) < TIMESTAMP_DIFF(patient.birthDate , TIMESTAMP_TRUNC(patient.birthDate , MONTH, 'America/Los_Angeles'), SECOND) THEN CASE WHEN patient.birthDate  < CURRENT_TIMESTAMP()  THEN -1 ELSE 0 END ELSE CASE WHEN patient.birthDate  > CURRENT_TIMESTAMP()  THEN 1 ELSE 0 END END) AS INT64) / 12) END AS INT64))  >= 65 THEN '65 or Above'
ELSE 'Undefined'
END AS patient_age_tier,
        (CASE WHEN (CONCAT((regexp_replace(patient.name[Offset(0)].given[Offset(0)],'[0-9]','')), ' ',(regexp_replace(patient.name[Offset(0)].family,'[0-9]','')))) IN( SELECT (CONCAT((regexp_replace(patient.name[Offset(0)].given[Offset(0)],'[0-9]','')), ' ',(regexp_replace(patient.name[Offset(0)].family,'[0-9]',''))))
                              FROM `looker-private-demo.healthcare_demo_live.encounter`  AS encounter
                              LEFT JOIN UNNEST(encounter.type) as encounter__type
                              LEFT JOIN UNNEST(encounter__type.coding) as encounter__type__coding
                              LEFT JOIN `looker-private-demo.healthcare_demo_live.patient`  AS patient ON encounter.subject.patientId = patient.id

                              WHERE (encounter.period.start ) >= ((TIMESTAMP(FORMAT_TIMESTAMP('%F %H:%M:%E*S', TIMESTAMP_ADD(TIMESTAMP_TRUNC(TIMESTAMP(FORMAT_TIMESTAMP('%F %H:%M:%E*S', CURRENT_TIMESTAMP(), 'America/Los_Angeles')), DAY), INTERVAL -364 DAY)), 'America/Los_Angeles')))
                              AND (encounter.period.start ) < ((TIMESTAMP(FORMAT_TIMESTAMP('%F %H:%M:%E*S', TIMESTAMP_ADD(TIMESTAMP_ADD(TIMESTAMP_TRUNC(TIMESTAMP(FORMAT_TIMESTAMP('%F %H:%M:%E*S', CURRENT_TIMESTAMP(), 'America/Los_Angeles')), DAY), INTERVAL -364 DAY), INTERVAL 365 DAY)), 'America/Los_Angeles')))
                              AND (encounter__type__coding.display IN ('Encounter for \'check-up\'', 'Encounter for check up', 'Encounter for check up (procedure)'))
                              GROUP BY 1
                              ORDER BY 1) THEN 'Yes' ELSE 'No' END) AS patient_is_wellness_screened_in_the_past_year,
    patient__address.state  AS patient__address_state,
    patient__address.country  AS patient__address_country,
    CONCAT((CONCAT((regexp_replace(practitioner.name[Offset(0)].given[Offset(0)],'[0-9]','')),' ',(regexp_replace(practitioner.name[Offset(0)].family,'[0-9]','')))))  AS practitioner_investigator,
    CASE
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 0 THEN '00'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 0 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 60 THEN '01'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 60 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 120 THEN '02'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 120 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 180 THEN '03'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 180 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 240 THEN '04'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 240 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 300 THEN '05'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 300 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 720 THEN '06'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 720 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 1440 THEN '07'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 1440 THEN '08'
ELSE '09'
END AS encounter_length_of_stay_tier__sort_,
    CASE
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 0 THEN 'Below 0'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 0 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 60 THEN '0 to 59'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 60 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 120 THEN '60 to 119'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 120 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 180 THEN '120 to 179'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 180 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 240 THEN '180 to 239'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 240 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 300 THEN '240 to 299'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 300 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 720 THEN '300 to 719'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 720 AND (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  < 1440 THEN '720 to 1439'
WHEN (CAST(TIMESTAMP_DIFF(((-- spectacles: ignore
    encounter.period
).end
) , ((-- spectacles: ignore
    encounter.period
).start
) , MINUTE) AS INT64)
)  >= 1440 THEN '1440 or Above'
ELSE 'Undefined'
END AS encounter_length_of_stay_tier,
    case when ((-- spectacles: ignore
    encounter.class
).code
) = 'IMP' then 'Inpatient'
    when ((-- spectacles: ignore
    encounter.class
).code
) = 'AMB' then 'Ambulatory'
    when ((-- spectacles: ignore
    encounter.class
).code
) = 'EMER' then 'Emergency Department' end AS encounter_code_name,
    -- spectacles: ignore
    (-- spectacles: ignore
    encounter.class
).system  AS encounter_system,
    encounter__reason__coding.display  AS encounter__reason__coding_display,
    encounter__type__coding.display  AS encounter__type__coding_display,
    observation__category__coding.display  AS observation__category__coding_display,
    (-- spectacles: ignore
    encounter.subject
).patientId  AS encounter_patient_id,
    encounter.id  AS encounter_id,
    patient.us_core_ethnicity.text.value.string  AS patient_us_core_ethnicity,
        (DATE((-- spectacles: ignore
    encounter.period
).start , 'America/Los_Angeles')) AS admission_date,
        (DATE((-- spectacles: ignore
    encounter.period
).end , 'America/Los_Angeles')) AS discharge_date,
LAG(DATE((encounter.period).end),1) OVER (PARTITION BY patient.id ORDER BY DATE((encounter.period).start , 'America/Los_Angeles') ASC) as last_discharge_date,
(CASE WHEN DATE_DIFF(DATE((encounter.period).end , 'America/Los_Angeles'), LAG(DATE((encounter.period).end),1) OVER (PARTITION BY patient.id ORDER BY DATE((encounter.period).start , 'America/Los_Angeles') ASC), DAY) <= 7 THEN TRUE
    WHEN DATE_DIFF(DATE((encounter.period).end , 'America/Los_Angeles'), LAG(DATE((encounter.period).end),1) OVER (PARTITION BY patient.id ORDER BY DATE((encounter.period).start , 'America/Los_Angeles') ASC), DAY) > 7 THEN FALSE
    ELSE NULL
    END) as readmission_within_7


FROM `looker-private-demo.healthcare_demo_live.encounter`  AS encounter
LEFT JOIN UNNEST((-- spectacles: ignore
    encounter.participant
)) as encounter__participant
LEFT JOIN UNNEST((-- spectacles: ignore
    encounter.reason
)) as encounter__reason
LEFT JOIN UNNEST((-- spectacles: ignore
    encounter__reason.coding
)) as encounter__reason__coding
LEFT JOIN UNNEST((-- spectacles: ignore
    encounter.type
)) as encounter__type
LEFT JOIN UNNEST((-- spectacles: ignore
    encounter__type.coding
)) as encounter__type__coding
LEFT JOIN `looker-private-demo.healthcare_demo_live.patient`  AS patient ON ((-- spectacles: ignore
    encounter.subject
).patientId
) = patient.id
LEFT JOIN UNNEST((-- spectacles: ignore
    patient.address
)) as patient__address
LEFT JOIN `looker-private-demo.healthcare_demo_live.observation`  AS observation ON ((-- spectacles: ignore
    observation.context
).encounterId
) = encounter.id
LEFT JOIN UNNEST((-- spectacles: ignore
    observation.category
)) as observation__category
LEFT JOIN UNNEST(observation__category.coding) as observation__category__coding
LEFT JOIN `looker-private-demo.healthcare_demo_live.practitioner`  AS practitioner ON practitioner.id = ((-- spectacles: ignore
    encounter__participant.individual
).practitionerId
)
WHERE ((-- spectacles: ignore
    encounter.period
).start ) >= (TIMESTAMP('2021-01-01 00:00:00', 'America/Los_Angeles')) ;;
  }
}

view: healthcare_bqml_eval1 {
  derived_table: {
    sql: SELECT * FROM ML.EVALUATE(MODEL `looker-private-demo.healthcare_demo_live.automl_classifier3`,
              (
              SELECT *
              FROM ${healthcare_bqml_input1.SQL_TABLE_NAME}
              WHERE readmission_within_7 IS NOT NULL
              )
              ) ;;
    persist_for: "72 hours"
  }

  dimension: precision {
    type: number
    sql: ${TABLE}.precision ;;
    value_format_name: percent_1
  }

  dimension: recall {
    type: number
    sql: ${TABLE}.recall ;;
    value_format_name: percent_1
  }

  dimension: accuracy {
    type: number
    sql: ${TABLE}.accuracy ;;
    value_format_name: percent_1
  }

  dimension: f1_score {
    type: number
    sql: ${TABLE}.f1_score ;;
    value_format_name: percent_1
  }

  dimension: log_loss {
    type: number
    sql: ${TABLE}.log_loss ;;
    value_format_name: percent_1
  }

  dimension: roc_auc {
    type: number
    sql: ${TABLE}.roc_auc ;;
    value_format_name: percent_1
  }

  set: detail {
    fields: [
      precision,
      recall,
      accuracy,
      f1_score,
      log_loss,
      roc_auc
    ]
  }
}

view: healthcare_training_info1 {
  derived_table: {
    sql:  SELECT * FROM ML.TRAINING_INFO(MODEL `looker-private-demo.healthcare_demo_live.automl_classifier3`);;
  }

  dimension: training_run {
    type: number
    sql: ${TABLE}.training_run ;;
  }

  dimension: iteration {
    type: number
    sql: ${TABLE}.iteration ;;
  }

  dimension: loss {
    type: number
    sql: ${TABLE}.loss ;;
  }

  dimension: eval_loss {
    type: number
    sql: ${TABLE}.eval_loss ;;
  }

  dimension: learning_rate {
    type: number
    sql: ${TABLE}.learning_rate ;;
  }

  dimension: duration_minutes {
    type: number
    sql: ${TABLE}.duration_ms / 60000;;
  }
}

view: healthcare_bqml_confusion_matrix {
 derived_table: {
   sql: SELECT * FROM ML.CONFUSION_MATRIX(
            MODEL`healthcare_demo_live.automl_classifier3`,
      (SELECT * FROM ${healthcare_bqml_input1.SQL_TABLE_NAME}
      WHERE readmission_within_7 IS NOT NULL))
 ;;
  persist_for: "72 hours"
 }
  dimension: expected_label {}
  dimension: false {}
  dimension: true {}
}

view: healthcare_bqml_predict1 {
  derived_table: {
    sql: SELECT * FROM ML.PREDICT(MODEL `healthcare_demo_live.automl_classifier3`,
          (
            SELECT *
            FROM ${healthcare_bqml_input1.SQL_TABLE_NAME}
            WHERE readmission_within_7 IS NOT NULL)
          ) ;;
    persist_for: "72 hours"
  }
}

view: bqml_predict {
  derived_table: {
    sql: SELECT * FROM ${healthcare_bqml_predict1.SQL_TABLE_NAME}
                  LEFT JOIN UNNEST (predicted_readmission_within_7_probs) as probs;;
  }

  measure: count {
    type: count
  }

  dimension: patient_id {
    type: string
    sql: ${TABLE}.patient_id ;;
  }

  dimension: patient_name {
    type: string
    sql: ${TABLE}.patient_name ;;
  }

  dimension: practitioner_gender {
    type: string
    sql: ${TABLE}.practitioner_gender ;;
  }

  dimension: patient_us_core_race {
    type: string
    sql: ${TABLE}.patient_us_core_race ;;
  }

  dimension: patient_age_tier__sort_ {
    type: string
    sql: ${TABLE}.patient_age_tier__sort_ ;;
  }

  dimension: patient_age_tier {
    type: string
    sql: ${TABLE}.patient_age_tier ;;
  }

  dimension: patient_is_wellness_screened_in_the_past_year {
    type: string
    sql: ${TABLE}.patient_is_wellness_screened_in_the_past_year ;;
  }

  dimension: patient__address_state {
    type: string
    sql: ${TABLE}.patient__address_state ;;
  }

  dimension: patient__address_country {
    type: string
    sql: ${TABLE}.patient__address_country ;;
  }

  dimension: practitioner_investigator {
    type: string
    sql: ${TABLE}.practitioner_investigator ;;
  }

  dimension: encounter_length_of_stay_tier__sort_ {
    type: string
    sql: ${TABLE}.encounter_length_of_stay_tier__sort_ ;;
  }

  dimension: encounter_length_of_stay_tier {
    type: string
    sql: ${TABLE}.encounter_length_of_stay_tier ;;
  }

  dimension: encounter_code_name {
    type: string
    sql: ${TABLE}.encounter_code_name ;;
  }

  dimension: encounter_system {
    type: string
    sql: ${TABLE}.encounter_system ;;
  }

  dimension: encounter__reason__coding_display {
    type: string
    sql: ${TABLE}.encounter__reason__coding_display ;;
  }

  dimension: encounter__type__coding_display {
    type: string
    sql: ${TABLE}.encounter__type__coding_display ;;
  }

  dimension: observation__category__coding_display {
    type: string
    sql: ${TABLE}.observation__category__coding_display ;;
  }

  dimension: encounter_patient_id {
    type: string
    sql: ${TABLE}.encounter_patient_id ;;
  }

  dimension: encounter_id {
    primary_key: yes
    type: string
    sql: ${TABLE}.encounter_id ;;
  }

  dimension: patient_us_core_ethnicity {
    type: string
    sql: ${TABLE}.patient_us_core_ethnicity ;;
  }

  dimension: admission_date {
    type: date
    datatype: date
    sql: ${TABLE}.admission_date ;;
  }

  dimension: discharge_date {
    type: date
    datatype: date
    sql: ${TABLE}.discharge_date ;;
  }

  dimension: last_discharge_date {
    type: date
    datatype: date
    sql: ${TABLE}.last_discharge_date ;;
  }

  dimension: readmission_within_7 {
    type: string
    sql: ${TABLE}.readmission_within_7 ;;
  }

  dimension: predicted_readmission_within_7 {
    type: yesno
  }
  dimension: predicted_readmission_within_7_probs {hidden:yes}

  dimension: label  {type: string }

  dimension: prob {
    type: number
    sql: ${TABLE}.prob ;;
  }

  measure: avg_prob {
    type: number
    sql: AVG(${TABLE}.prob) ;;
    value_format_name: percent_2
    sql_distinct_key: ${encounter_id} ;;
  }

}
